# This file comes from a basic template for GitLab CI/CD

default:
  image: openjdk:11-jdk

stages:
  - test

variables:
  # Define the SDK version and build tools version
  ANDROID_SDK_VERSION: "24"
  ANDROID_BUILD_TOOLS_VERSION: "24.0.0"

  # Define where to store the SDK and the NDK
  ANDROID_SDK_ROOT: "$CI_PROJECT_DIR/android-sdk"
  ANDROID_HOME: "$ANDROID_SDK_ROOT"
  ANDROID_NDK_ROOT: "$CI_PROJECT_DIR/android-ndk"
  ANDROID_NDK_HOME: "$ANDROID_NDK_ROOT"

  # Define the gradle wrapper path
  GRADLE_WRAPPER: "$CI_PROJECT_DIR/gradlew"

cache:
  # Cache the SDK and the NDK to speed up the build
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
  paths:
    - .android-sdk/
    - .android-ndk/

before_script:
  # Install the SDK and the NDK
  - bash scripts/install-sdk.sh
  - bash scripts/install-ndk.sh

  # Make the gradle wrapper executable
  - chmod +x $GRADLE_WRAPPER

test:
  stage: test
  script:
    # Run the unit tests
    - $GRADLE_WRAPPER :app:testDebugUnitTest

    # Run the espresso tests
    - $GRADLE_WRAPPER :app:connectedDebugAndroidTest
