stages:
  - build
  - test

cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"

before_script:
  # Make the gradle wrapper executable.
  - chmod +x ./gradlew

Build:
  image: ethrozee/android
  interruptible: true
  tags:
    - dalfcs_docker_kvm
  stage: build
  script:
    # Build the application.
    - ./gradlew assembleDebug

  artifacts:
    paths:
      # Give the results of compilation to the next stage.
      - app/build/
      - .gradle/

UnitTests:
  image: ethrozee/android
  interruptible: true
  tags:
    - dalfcs_docker_kvm
  stage: test
  script:
    # Run the unit tests.
    - ./gradlew :app:testDebugUnitTest

  after_script:
    # Reposition test results.
    - mv app/build/reports/tests/testDebugUnitTest testDebugUnitTest

  artifacts:
    when: always
    expire_in: 30 days
    paths:
      - testDebugUnitTest/

# ConnectedTests:
#   image: ethrozee/android-emulator
#   interruptible: true
#   tags:
#     - dalfcs_docker_kvm
#   stage: test
#   script:
#     # Launch the android emulator.
#     - $EMU_HEADLESS

#     # Run the connected tests with logcat output.
#     - adb logcat *:S TestRunner:V -T 1 & LOGCAT_PID=$!
#     - ./gradlew :app:connectedDebugAndroidTest
 
#   after_script:
#     # Stop logcat if it is still running.
#     - if [ -n "$LOGCAT_PID" ] ; then kill $LOGCAT_PID; fi

#     # Reposition test results.
#     - mv app/build/reports/androidTests/connected/debug connectedDebugAndroidTest

#   artifacts:
#     when: always
#     expire_in: 30 days
#     paths:
#       - connectedDebugAndroidTest/
