# This file comes from a basic template for GitLab CI/CD

default:
  image: androidsdk/android-24:latest

stages:
  - test

variables:
  # Define the gradle wrapper path
  GRADLE_WRAPPER: "$CI_PROJECT_DIR/gradlew"

cache:
  # Cache the SDK and the NDK to speed up the build
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"

before_script:
  # Install kvm for hardware virtualization.
  - yes | apt install qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils

  # Make sure kvm installed.
  - kvm-ok

  # Create an android emulator and launch it.
  - avdmanager create avd -n default_avd -k "system-images;android-24;google_apis;x86_64" --device "pixel"
  - emulator -avd default_avd -no-window -no-audio &

  # Make the gradle wrapper executable
  - chmod +x $GRADLE_WRAPPER

test:
  stage: test
  script:
    # Run the unit tests
    - $GRADLE_WRAPPER :app:testDebugUnitTest

    # Run the espresso tests
    - $GRADLE_WRAPPER :app:connectedDebugAndroidTest
