# This file comes from a basic template for GitLab CI/CD

default:
  image: docker.io/ethrozee/android-emulator
  #devices:
  #  - /dev/kvm:/dev/kvm

stages:
  - test

variables:
  # Define the gradle wrapper path
  GRADLE_WRAPPER: "$CI_PROJECT_DIR/gradlew"

cache:
  # Cache the SDK and the NDK to speed up the build
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"

before_script:
  # Make the gradle wrapper executable
  - chmod +x $GRADLE_WRAPPER

JUnitTest:
  stage: test
  script:
    # Run the unit tests
    - $GRADLE_WRAPPER :app:testDebugUnitTest
  artifacts:
    when: always
    paths:
      - JUnitTest-results.xml
    reports:
      junit: app/build/test-results/testDebugUnitTest/TEST-*.xml

#EspressoTest:
#  stage: test
#  script:
#    # Launch the android emulator.
#    - $EMU_HEADLESS
#    
#    # Run the espresso tests
#    - $GRADLE_WRAPPER :app:connectedDebugAndroidTest
#  artifacts:
#    when: always
#    reports:
#      junit: app/build/test-results/connectedDebugAndroidTest/TEST-*.xml
