stages:
  - build
  - test

variables:
  GRADLE_WRAPPER: "$CI_PROJECT_DIR/gradlew"
  UNIT_TEST: "testDebugUnitTest"
  CONNECTED_TEST: "connectedDebugAndroidTest"

cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"

before_script:
  # Make the gradle wrapper executable.
  - chmod +x ./gradlew

Build:
  image: ethrozee/android
  interruptible: true
  tags:
    - dalfcs_docker_kvm
  stage: build
  script:
    # Build the application.
    - ./gradlew assembleDebug

  artifacts:
    paths:
      # Give the compiled artifacts to the next stage.
      - app/build/
      # Pass the gradle install to the next builds to avoid downloading again.
      - .gradle/

UnitTests:
  image: ethrozee/android
  interruptible: true
  tags:
    - dalfcs_docker_kvm
  stage: test
  script:
    # Run the unit tests.
    - ./gradlew :app:testDebugUnitTest

  after_script:
    # Reposition test results.
    - mv app/build/reports/tests/testDebugUnitTest testDebugUnitTest

  artifacts:
    when: always
    expire_in: 30 days
    paths:
      - testDebugUnitTest/

ConnectedTests:
  image: ethrozee/android-emulator
  interruptible: true
  tags:
    - dalfcs_docker_kvm
  stage: test
  script:
    # Launch the android emulator.
    - $EMU_HEADLESS

    # Run the connected tests.
    - ./gradlew :app:connectedDebugAndroidTest

  after_script:
    # Reposition test results.
    - mv app/build/reports/androidTests/connected/debug connectedDebugAndroidTest

  artifacts:
    when: always
    expire_in: 30 days
    paths:
      - connectedDebugAndroidTest/
