# This file comes from a basic template for GitLab CI/CD

default:
  image: androidsdk/android-24:latest

stages:
  - JUnitTest
  - EspressoTest

variables:
  # Define the gradle wrapper path
  GRADLE_WRAPPER: "$CI_PROJECT_DIR/gradlew"

cache:
  # Cache the SDK and the NDK to speed up the build
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"

before_script:
  # Check for hardware virtualization support.
  - egrep -c '(vmx|svm)' /proc/cpuinfo

  # Create an android emulator and launch it.
  - avdmanager create avd -n default_avd -k "system-images;android-24;google_apis;x86_64" --device "pixel"
  - emulator -avd default_avd -no-window -no-audio &

  # Make the gradle wrapper executable
  - chmod +x $GRADLE_WRAPPER

test:
  stage: JUnitTest
  script:
    # Run the unit tests
    - $GRADLE_WRAPPER :app:testDebugUnitTest

  stage: EspressoTest
  script:
    # Run the espresso tests
    - $GRADLE_WRAPPER :app:connectedDebugAndroidTest
