# This file comes from a basic template for GitLab CI/CD

default:
  image: androidsdk/android-24:latest

stages:
  - test

variables:
  # Define the gradle wrapper path
  GRADLE_WRAPPER: "$CI_PROJECT_DIR/gradlew"

cache:
  # Cache the SDK and the NDK to speed up the build
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"

before_script:
  # Create an android emulator and launch it.
  # - avdmanager create avd -n first_avd --abi google_apis/x86_64 -k "system-images;android-24;google_apis;x86_64"
  # - emulator -avd first_avd -no-window -no-audio &

  # View installed files.
  - sdkmanager --list
  - avdmanager list avd

test:
  stage: test
  script:
    # Run the unit tests
    - $GRADLE_WRAPPER :app:testDebugUnitTest

    # Run the espresso tests
    - $GRADLE_WRAPPER :app:connectedDebugAndroidTest
