stages:
  - build
  - test

cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"

before_script:
  # Make the gradle wrapper executable.
  - chmod +x ./gradlew

Build:
  image: ethrozee/android
  interruptible: true
  tags:
    - dalfcs_docker_kvm
  stage: build
  script:
    # Build the application.
    - ./gradlew assembleDebug

  artifacts:
    paths:
      # Give the results of compilation to the next stage.
      - app/build/
      - .gradle/

UnitTests:
  image: ethrozee/android
  interruptible: true
  tags:
    - dalfcs_docker_kvm
  stage: test
  script:
    # Run the unit tests.
    - ./gradlew :app:testDebugUnitTest

  after_script:
    # Reposition test results.
    - mv app/build/reports/tests/testDebugUnitTest testDebugUnitTest

  artifacts:
    when: always
    expire_in: 30 days
    paths:
      - testDebugUnitTest/

ConnectedTests:
  image: ethrozee/android
  interruptible: true
  tags:
    - dalfcs_docker_kvm
  stage: test
  variables:
    GITHUB_REPO: csci3130_group_3
    GITHUB_USER: ethroz
    # This token only works for accessing the public repo.
    GITHUB_TOKEN: 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
  script:
    # Build the android connected test apk.
    - ./gradlew assembleDebugAndroidTest

    # Start a github action to run the connected tests.
    - 'curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
    -H "Accept: application/vnd.github.v3+json" \
    https://api.github.com/repos/$GITHUB_USER/$GITHUB_REPO/dispatches \
    -d "{\
      "event_type": "trigger-test",\
      "client_payload": {\
        "project_id": "$CI_PROJECT_NAME",\
        "job_id": "$CI_JOB_ID",\
        "branch": "$CI_COMMIT_BRANCH"\
      }\
    }"'

  after_script:
    # Move the apks to the root folder.
    - find app/build/outputs --name "*.apk" -exec mv {} apks +

  artifacts:
    when: always
    expire_in: 30 days
    paths:
      - apks/

# ConnectedTests:
#   image: ethrozee/android-emulator
#   interruptible: true
#   tags:
#     - dalfcs_docker_kvm
#   stage: test
#   script:
#     # Launch the android emulator.
#     - $EMU_HEADLESS

#     # Run the connected tests with logcat output.
#     - adb logcat *:S TestRunner:V -T 1 & LOGCAT_PID=$!
#     - ./gradlew :app:connectedDebugAndroidTest
 
#   after_script:
#     # Stop logcat if it is still running.
#     - if [ -n "$LOGCAT_PID" ] ; then kill $LOGCAT_PID; fi

#     # Reposition test results.
#     - mv app/build/reports/androidTests/connected/debug connectedDebugAndroidTest

#   artifacts:
#     when: always
#     expire_in: 30 days
#     paths:
#       - connectedDebugAndroidTest/
