# This file comes from a basic template for GitLab CI/CD

default:
  image: androidsdk/android-24:latest

stages:
  - build
  - test

variables:
  # Define the gradle wrapper path
  GRADLE_WRAPPER: "$CI_PROJECT_DIR/gradlew"

cache:
  # Cache the SDK and the NDK to speed up the build
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"

before_script:
  # Launch the android emulator.
  - $EMU_HEADLESS

  # Make the gradle wrapper executable
  - chmod +x $GRADLE_WRAPPER

build:
  stage: build
  script:
    # rebuild command
    - $GRADLE_WRAPPER build --refresh-dependencies

JUnitTest:
  stage: test
  script:
    # Run the unit tests
    - $GRADLE_WRAPPER :app:testDebugUnitTest --console verbose

EspressoTest:
  stage: test
  script:
    # Run the espresso tests
    - $GRADLE_WRAPPER :app:connectedDebugAndroidTest --console verbose
