default:
image: ethrozee/android-emulator

stages:
  - test

variables:
  GRADLE_WRAPPER: "$CI_PROJECT_DIR/gradlew"
  UNIT_TEST: "testDebugUnitTest"
  CONNECTED_TEST: "connectedDebugAndroidTest"

cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"

before_script:
  # Make the gradle wrapper executable
  - chmod +x $GRADLE_WRAPPER

UnitTests:
  stage: test
  script:
    # Run the unit tests
    - $GRADLE_WRAPPER :app:$UNIT_TEST
  after_script:
    # Reposition test results
    - mv ./app/build/reports/tests/$UNIT_TEST ./$UNIT_TEST
  artifacts:
    when: always
    paths:
      - $UNIT_TEST
    reports:
      junit: $UNIT_TEST

ConnectedTests:
  tags: 
    - dalfcs_docker_kvm
  stage: test
  script:
    # Launch the android emulator.
    - $EMU_HEADLESS
    
    # Run the espresso tests
    - $GRADLE_WRAPPER :app:$CONNECTED_TEST
  after_script:
    # Reposition test results
    - mv ./app/build/reports/androidTests/connected/debug/ ./$CONNECTED_TEST
  artifacts:
    when: always
    paths:
      - $CONNECTED_TEST
    reports:
      junit: $CONNECTED_TEST
