default:
  image: ethrozee/android-emulator

stages:
  - test

variables:
  GRADLE_WRAPPER: "$CI_PROJECT_DIR/gradlew"
  CONNECTED_TEST: "connectedDebugAndroidTest"

cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"

before_script:
  # Make the gradle wrapper executable
  - chmod +x $GRADLE_WRAPPER

test:
  tags: 
    - dalfcs_docker_kvm
  stage: test
  script:
    # Launch the android emulator.
    - export HW_ACCEL_OVERRIDE="-accel off"
    - $EMU_HEADLESS
    
    # Run the connected tests
    - $GRADLE_WRAPPER :app:$CONNECTED_TEST
  after_script:
    # Reposition test results
    - mv ./app/build/reports/tests/$CONNECTED_TEST ./$CONNECTED_TEST
  artifacts:
    when: always
    paths:
      - $CONNECTED_TEST
