name: Run connected tests

on:
  repository_dispatch:
    types: [trigger-test]

jobs:
  ConnectedTests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api-level: [28, 30, 32, 34]
    steps:
      - name: Download APKs from Gitlab
        env:
          GITLAB_JOB_URL: ${{ github.event.client_payload.job_url }}
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          curl -o artifacts.zip -L -H "PRIVATE-TOKEN: $GITLAB_TOKEN" "$GITLAB_JOB_URL"
          unzip artifacts.zip && mv apks/* .
      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
      - name: Run connected tests
        uses: ReactiveCircus/android-emulator-runner@v2
        env:
          PACKAGE: com.example.csci3130_group_3
        with:
          api-level: ${{ matrix.api-level }}
          target: google_apis
          arch: x86
          profile: small
          script: |
            adb install app-debug.apk
            adb install app-debug-androidTest.apk
            adb shell am instrument -w $PACKAGE/androidx.test.runner.AndroidJUnitRunner
