name: Run connected tests

on:
  repository_dispatch:
    types: [trigger-test]

jobs:
  ConnectedTests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.branch }}
      - name: Download APKs from Gitlab
        env:
          GITLAB_PROJECT_ID: ${{ github.event.client_payload.project_id }}
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          curl -H "Authorization: Bearer $GITLAB_TOKEN" -L -o app-debug.apk "https://gitlab.com/api/v4/projects/$GITLAB_PROJECT_ID/jobs/${{ github.event.client_payload.job_id }}/artifacts/apks/app-debug.apk"
          curl -H "Authorization: Bearer $GITLAB_TOKEN" -L -o app-debug-androidTest.apk "https://gitlab.com/api/v4/projects/$GITLAB_PROJECT_ID/jobs/${{ github.event.client_payload.job_id }}/artifacts/apks/app-debug-androidTest.apk"
      - name: Run connected tests
        uses: ReactiveCircus/android-emulator-runner@v2
        env:
          PACKAGE: com.example.csci3130_group_3
        with:
          api-level: 28
          target: google_apis
          arch: x86
          script: |
            adb install app-debug.apk
            adb install app-debug-androidTest.apk
            adb shell am instrument -w $PACKAGE/androidx.test.runner.AndroidJUnitRunner
