name: Run connected tests

on:
  workflow_dispatch:
    inputs:
      commit:
        description: 'The unique hash of the commit'
        required: true
      proj_id:
        description: 'The ID of the project'
        required: true
      job_id:
        description: 'The ID of the job'
        required: true

run-name: ${{ github.event.inputs.commit }}

jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        env:
          COMMIT: ${{ github.event.inputs.commit }}
          PROJECT_ID: ${{ github.event.inputs.proj_id }}
          JOB_ID: ${{ github.event.inputs.job_id }}
          DOMAIN: ${{ secrets.DOMAIN }}
          OWNER: ${{ secrets.OWNER }}
          PROJECT: ${{ secrets.PROJECT }}
          USER: ${{ secrets.USER }}
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          git clone "https://$USER:$TOKEN@$DOMAIN/$OWNER/$PROJECT.git"
          cd $PROJECT
          git checkout $COMMIT
          chmod +x ./gradlew
          curl -s -o artifacts.zip -L -H "PRIVATE-TOKEN: $TOKEN" "https://$DOMAIN/api/v4/projects/$PROJECT_ID/jobs/$JOB_ID/artifacts"
          unzip artifacts.zip

  ConnectedTests:
    needs: Setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api-level: [28, 30, 32, 34]
    steps:
      - name: Create artifacts
        run: |
          echo "Hi ${{ matrix.api-level }}" > test${{ matrix.api-level }}.txt
      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: testResultsAPI${{ matrix.api-level }}
          path: test.txt
